# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tasks.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btasks.proto\x12\x05tasks\"c\n\x1aRentAndStartSessionRequest\x12\x0e\n\x06gpu_id\x18\x01 \x01(\x05\x12\x15\n\rcompute_units\x18\x02 \x01(\x05\x12\r\n\x05model\x18\x03 \x01(\t\x12\x0f\n\x07\x64\x61taset\x18\x04 \x01(\t\"R\n\x15UpdateTrainingRequest\x12\x12\n\nsession_id\x18\x01 \x01(\x05\x12\r\n\x05\x65poch\x18\x02 \x01(\x05\x12\x16\n\x0eparameter_hash\x18\x03 \x01(\t\"E\n\x17\x43hangeAggregatorRequest\x12\x12\n\nsession_id\x18\x01 \x01(\x05\x12\x16\n\x0enew_aggregator\x18\x02 \x01(\t\"#\n\x11ReleaseGPURequest\x12\x0e\n\x06gpu_id\x18\x01 \x01(\x05\"%\n\x0fSessionResponse\x12\x12\n\nsession_id\x18\x01 \x01(\x05\"!\n\x0fGenericResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xb3\x02\n\x0bTaskService\x12P\n\x13RentAndStartSession\x12!.tasks.RentAndStartSessionRequest\x1a\x16.tasks.SessionResponse\x12\x46\n\x0eUpdateTraining\x12\x1c.tasks.UpdateTrainingRequest\x1a\x16.tasks.GenericResponse\x12J\n\x10\x43hangeAggregator\x12\x1e.tasks.ChangeAggregatorRequest\x1a\x16.tasks.GenericResponse\x12>\n\nReleaseGPU\x12\x18.tasks.ReleaseGPURequest\x1a\x16.tasks.GenericResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tasks_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RENTANDSTARTSESSIONREQUEST']._serialized_start=22
  _globals['_RENTANDSTARTSESSIONREQUEST']._serialized_end=121
  _globals['_UPDATETRAININGREQUEST']._serialized_start=123
  _globals['_UPDATETRAININGREQUEST']._serialized_end=205
  _globals['_CHANGEAGGREGATORREQUEST']._serialized_start=207
  _globals['_CHANGEAGGREGATORREQUEST']._serialized_end=276
  _globals['_RELEASEGPUREQUEST']._serialized_start=278
  _globals['_RELEASEGPUREQUEST']._serialized_end=313
  _globals['_SESSIONRESPONSE']._serialized_start=315
  _globals['_SESSIONRESPONSE']._serialized_end=352
  _globals['_GENERICRESPONSE']._serialized_start=354
  _globals['_GENERICRESPONSE']._serialized_end=387
  _globals['_TASKSERVICE']._serialized_start=390
  _globals['_TASKSERVICE']._serialized_end=697
# @@protoc_insertion_point(module_scope)
