# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import tasks_pb2 as tasks__pb2


class TaskServiceStub(object):
    """Define a service for handling GPU-related tasks and training sessions
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RentGPU = channel.unary_unary(
                '/tasks.TaskService/RentGPU',
                request_serializer=tasks__pb2.RentGPURequest.SerializeToString,
                response_deserializer=tasks__pb2.GenericResponse.FromString,
                )
        self.ReleaseGPU = channel.unary_unary(
                '/tasks.TaskService/ReleaseGPU',
                request_serializer=tasks__pb2.ReleaseGPURequest.SerializeToString,
                response_deserializer=tasks__pb2.GenericResponse.FromString,
                )
        self.StartTrainingSession = channel.unary_unary(
                '/tasks.TaskService/StartTrainingSession',
                request_serializer=tasks__pb2.StartTrainingSessionRequest.SerializeToString,
                response_deserializer=tasks__pb2.SessionResponse.FromString,
                )
        self.UpdateModelParameters = channel.unary_unary(
                '/tasks.TaskService/UpdateModelParameters',
                request_serializer=tasks__pb2.UpdateModelParametersRequest.SerializeToString,
                response_deserializer=tasks__pb2.UpdateModelParametersResponse.FromString,
                )


class TaskServiceServicer(object):
    """Define a service for handling GPU-related tasks and training sessions
    """

    def RentGPU(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseGPU(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartTrainingSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateModelParameters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RentGPU': grpc.unary_unary_rpc_method_handler(
                    servicer.RentGPU,
                    request_deserializer=tasks__pb2.RentGPURequest.FromString,
                    response_serializer=tasks__pb2.GenericResponse.SerializeToString,
            ),
            'ReleaseGPU': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseGPU,
                    request_deserializer=tasks__pb2.ReleaseGPURequest.FromString,
                    response_serializer=tasks__pb2.GenericResponse.SerializeToString,
            ),
            'StartTrainingSession': grpc.unary_unary_rpc_method_handler(
                    servicer.StartTrainingSession,
                    request_deserializer=tasks__pb2.StartTrainingSessionRequest.FromString,
                    response_serializer=tasks__pb2.SessionResponse.SerializeToString,
            ),
            'UpdateModelParameters': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateModelParameters,
                    request_deserializer=tasks__pb2.UpdateModelParametersRequest.FromString,
                    response_serializer=tasks__pb2.UpdateModelParametersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tasks.TaskService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TaskService(object):
    """Define a service for handling GPU-related tasks and training sessions
    """

    @staticmethod
    def RentGPU(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tasks.TaskService/RentGPU',
            tasks__pb2.RentGPURequest.SerializeToString,
            tasks__pb2.GenericResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReleaseGPU(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tasks.TaskService/ReleaseGPU',
            tasks__pb2.ReleaseGPURequest.SerializeToString,
            tasks__pb2.GenericResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StartTrainingSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tasks.TaskService/StartTrainingSession',
            tasks__pb2.StartTrainingSessionRequest.SerializeToString,
            tasks__pb2.SessionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateModelParameters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tasks.TaskService/UpdateModelParameters',
            tasks__pb2.UpdateModelParametersRequest.SerializeToString,
            tasks__pb2.UpdateModelParametersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
