# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tasks.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btasks.proto\x12\x05tasks\"7\n\x0eRentGPURequest\x12\x0e\n\x06gpu_id\x18\x01 \x01(\x05\x12\x15\n\rcompute_units\x18\x02 \x01(\x05\"T\n\x0fModelParameters\x12\r\n\x05\x65poch\x18\x01 \x01(\x05\x12\x0e\n\x06\x64\x65vice\x18\x02 \x01(\t\x12\x10\n\x08strategy\x18\x03 \x01(\t\x12\x10\n\x08training\x18\x04 \x01(\t\"k\n\x1bStartTrainingSessionRequest\x12\x0e\n\x06gpu_id\x18\x01 \x01(\x05\x12\x12\n\nmodel_data\x18\x02 \x01(\x0c\x12\x0f\n\x07\x64\x61taset\x18\x03 \x01(\x0c\x12\x17\n\x0fhyperparameters\x18\x04 \x01(\x0c\"#\n\x11ReleaseGPURequest\x12\x0e\n\x06gpu_id\x18\x01 \x01(\x05\"%\n\x0fSessionResponse\x12\x12\n\nsession_id\x18\x01 \x01(\x05\"!\n\x0fGenericResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"L\n\x1cUpdateModelParametersRequest\x12\x12\n\nsession_id\x18\x01 \x01(\x05\x12\x18\n\x10model_parameters\x18\x02 \x01(\x0c\"/\n\x1dUpdateModelParametersResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xbf\x02\n\x0bTaskService\x12\x38\n\x07RentGPU\x12\x15.tasks.RentGPURequest\x1a\x16.tasks.GenericResponse\x12>\n\nReleaseGPU\x12\x18.tasks.ReleaseGPURequest\x1a\x16.tasks.GenericResponse\x12R\n\x14StartTrainingSession\x12\".tasks.StartTrainingSessionRequest\x1a\x16.tasks.SessionResponse\x12\x62\n\x15UpdateModelParameters\x12#.tasks.UpdateModelParametersRequest\x1a$.tasks.UpdateModelParametersResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tasks_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RENTGPUREQUEST']._serialized_start=22
  _globals['_RENTGPUREQUEST']._serialized_end=77
  _globals['_MODELPARAMETERS']._serialized_start=79
  _globals['_MODELPARAMETERS']._serialized_end=163
  _globals['_STARTTRAININGSESSIONREQUEST']._serialized_start=165
  _globals['_STARTTRAININGSESSIONREQUEST']._serialized_end=272
  _globals['_RELEASEGPUREQUEST']._serialized_start=274
  _globals['_RELEASEGPUREQUEST']._serialized_end=309
  _globals['_SESSIONRESPONSE']._serialized_start=311
  _globals['_SESSIONRESPONSE']._serialized_end=348
  _globals['_GENERICRESPONSE']._serialized_start=350
  _globals['_GENERICRESPONSE']._serialized_end=383
  _globals['_UPDATEMODELPARAMETERSREQUEST']._serialized_start=385
  _globals['_UPDATEMODELPARAMETERSREQUEST']._serialized_end=461
  _globals['_UPDATEMODELPARAMETERSRESPONSE']._serialized_start=463
  _globals['_UPDATEMODELPARAMETERSRESPONSE']._serialized_end=510
  _globals['_TASKSERVICE']._serialized_start=513
  _globals['_TASKSERVICE']._serialized_end=832
# @@protoc_insertion_point(module_scope)
